problem:
  name: "convection_1D"
  betta: 15
  t_max: 10

model:
  type: FNN
  params:
    hidden_layers: [128, 128, 128, 128]

model_target:
  _target_: multipinn.neural_network.${model.type}

regularization:
  type: Constant
  params:
    lambdas: [1, 1, 1]

regularization_target:
  _target_: multipinn.regularization.${regularization.type}Losses

generator:
  domain_points: 40_000
  bound_points: 5_000
  sampler: "Sobol"

trainer:
  num_epochs: 100_000
  grid_update: null
  random_seed: 42
  calc_loss: "mean" # "mean", "legacy"

visualization:
  grid_plot_points: 20_000
  save_period: 5000
  save_mode: "html"

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.9999

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

paths:
  save_dir: ${hydra:runtime.cwd}/examples/${problem.name}/artifacts/${model.type}_${regularization.type}_${generator.sampler}_${trainer.random_seed}_betta_${problem.betta}
